# .streamlit/secrets.toml

# Chiave API per i servizi Google Gemini
GEMINI_API_KEY = "AIzaSyD6D7tZmi11fB5aae7v68q367cyByTlcnU"

# -----------------------------------------------------------------------------
# IMPORTANTE: Il file 'secrets.toml' è già ignorato da Git e non verrà mai
# caricato nel repository per motivi di sicurezza.
# -----------------------------------------------------------------------------

# Percorso completo del file Excel che contiene lo storico delle attività.
# Nota: I backslash in Windows devono essere doppi (es. "C:\\Users\\...")
path_storico_db = "\\\\192.168.11.251\\Database_Tecnico_SMI\\cartella strumentale condivisa\\ALLEGRETTI\\Database_Report_Attivita.xlsm"

# Percorso completo del file Excel che gestisce i dati dei tecnici (contatti, turni, ecc.).
path_gestionale = "C:\\Users\\Coemi\\Desktop\\SCRIPT\\report-attivita-app\\Gestionale_Tecnici.xlsx"

# Percorso della cartella che contiene le giornaliere.
# L'app aggiungerà dinamicamente il nome del file mensile (es. "Giornaliera 09-2025.xlsm").
path_giornaliera_base = "\\\\192.168.11.251\\Database_Tecnico_SMI\\Giornaliere\\Giornaliere 2025"

# Nome del foglio Google Sheets per le risposte (usato dalla vecchia logica, può essere vuoto).
nome_foglio_risposte = "Report Attività Giornaliera (Risposte)"

# Percorso del file delle attività programmate (per le nuove dashboard).
path_attivita_programmate = "\\\\192.168.11.251\\Database_Tecnico_SMI\\cartella strumentale condivisa\\ALLEGRETTI\\ATTIVITA_PROGRAMMATE.xlsm"